server:
  applicationConnectors:
    - type: http
      port: 8080
      # Increase the number of acceptor threads for handling incoming connections
      acceptorThreads: 4
      # Increase the number of selector threads for I/O operations
      selectorThreads: 8
  adminConnectors:
    - type: http
      port: 8081
      acceptorThreads: 2
      selectorThreads: 4
logging:
  level: INFO